spring:
  application.name: eureka
server.port: 8761
security.basic.enabled: false
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
